Больше деталей
htmlacademy-javascript/2235875-kekstagram-32 pull request #3
Opened 2024-07-05 12:15 UTC by kristinaNoskova

2024-07-05 16:13 UTC, balesniy requested changes
обрати внимание на нейминг, он нужен чтобы потом не запутаться, где функция, а где значение

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +  const generatedValue = [];
массивы просят называть во множественном числе

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +function createRandomNumber(min, max) {
эта функция не возвращает число, она возвращает генератор случайных чисел, я бы назвал ее типа "getUniqRandomGenerator"

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +      if (generatedValue.includes(currentValue)) {
меня смущает маловероятный сценарий, когда за max итераций он не найдет уникальное число. что он тогда вернет?

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +const likes = createRandomNumber(15, 200);
это еще не лайки, это функция по производству лайков, так что тут что то вроде "getLikesCount"

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +const commentId = createRandomNumber(0, Math.floor(Math.random() * 200));
у тебя уже есть функция для получения случайного целого

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +const currentNumber = createSerialNumber(1, 25);
тут тоже функция а не номер

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +  const randomItem = array[Math.floor(Math.random() * array.length)];
используй  getRandomInteger и множественное число для массива

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +const arrayWithComment = Array.from({ length: 30 }, describesComment);
нужно придумать название во множественом числе

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +  const randomNumber = Math.floor(Math.random() * 30);
двойное перемешивание избыточно

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +  const mixedArray = array.sort(() => Math.random() - 0.5);
sort "портит" исходный массив, тут нужна тогда копия

2024-07-05 16:13 UTC, balesniy commented on js/main.js
> +const arrayWithPhoto = Array.from({ length: 25 }, describesPhoto);
photos

2024-07-07 11:05 UTC, kristinaNoskova commented on js/main.js
> +  const randomNumber = Math.floor(Math.random() * 30);
здесь нет двойного перемешивания. Сначала перемешиваю массив методом sort(), потом получаю рандомное число от 0 до 30.  И слайсом обрезаю столько элементов, сколько выдаст randomNumber, таким образом получаю пункт из тз "Количество комментариев к каждой фотографии — случайное число от 0 до 30".

2024-07-07 11:07 UTC, kristinaNoskova commented on js/main.js
> +  const mixedArray = array.sort(() => Math.random() - 0.5);
в рамках данного задания все-равно не допустимо исходный массив мешать? Ведь он больше нигде не переиспользуется и порядок элементов не важен.

2024-07-07 11:10 UTC, kristinaNoskova commented on js/main.js
> +function createRandomNumber(min, max) {
Такого рода названия нам в демонстрациях показывала академия. Я поэтому начинаю путаться с правильными наименованиями.
<img width="503" alt="Снимок экрана 2024-07-07 в 14 08 11" src="https://github.com/htmlacademy-javascript/2235875-kekstagram-32/assets/121613581/e2d6b4d6-f1d1-4fee-8983-a9e34de21af6">

2024-07-08 16:03 UTC, balesniy commented on js/main.js
> +const avatar = getUniqRandomGenerator(1, 6);
это функция

2024-07-08 16:05 UTC, balesniy commented on js/main.js
> +const descrPhotos = ['Город', 'cад', 'горы', 'озеро', 'река', 'лес'];
это константы

2024-07-08 16:06 UTC, balesniy commented on js/main.js
> +function getArrayElement(array) {
массивы нельзя называть "массив"

2024-07-08 16:07 UTC, balesniy commented on js/main.js
> +function getArrayElement(array) {
items / elements

2024-07-08 16:07 UTC, balesniy commented on js/main.js
> +  return randomItems;
randomItem - он один!!

2024-07-08 16:10 UTC, balesniy commented on js/main.js
> +function getRandomInteger(min, max) {
все функции стрелками!!

2024-07-08 16:13 UTC, balesniy commented on js/main.js
> +  const mixedArray = array.sort(() => Math.random() - 0.5);
https://ru.wikipedia.org/wiki/Тасование_Фишера_—_Йетса

2024-07-08 16:22 UTC, balesniy commented on js/main.js
> +    for (let i = min; i <= max; i++) {
[1,2,3,4,5]

for (1-3) {
возьми одно число  и вычеркни его из списка доступных

}

2024-07-10 19:41 UTC, balesniy commented on js/main.js
> +const DESCR_PHOTOS = ['Город', 'cад', 'горы', 'озеро', 'река', 'лес'];
не экономь буквы)

2024-07-10 19:42 UTC, balesniy commented on js/main.js
> +function getArrayElement(elements) {
все функции нужно сделать стрелками

2024-07-10 19:43 UTC, balesniy commented on js/main.js
> +    message: Array.from({ length: getRandomInteger(1, 2) }, () => getArrayElement(TEXT_MESSAGES)),
сообщение должно быть строкой, нужно соединить массив

2024-07-10 19:43 UTC, balesniy commented on js/main.js
> +  return: {
тут синтаксис проверь

2024-07-10 19:45 UTC, balesniy commented on js/main.js
> +const describesPhoto = () => ({
такой синтаксис сразу возвращает объект, return не нужен

2024-07-10 19:45 UTC, balesniy commented on js/main.js
> +const arrayWithPhotos = () => Array.from({ length: 25 }, describesPhoto);
в названии функции нужен глагол

2024-07-11 08:56 UTC, merged